//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Vct.rc
//
#define IDS_VCT                         1
#define IDD_ABOUTBOX_VCT                1
#define IDB_VCT                         1
#define IDI_ABOUTDLL                    1
#define IDS_VCT_PPG                     2
#define IDC_POINTER                     104
#define IDS_VCT_PPG_CAPTION             200
#define IDD_PROPPAGE_VCT                200
#define IDS_GAME_PPG_CAPTION            200
#define IDS_GAME_TITLE                  201
#define IDS_GMGR_NAME                   203
#define IDS_GMGR_SLOTLIST               204
#define IDS_GMGR_MOREINFO               205
#define IDC_HINT_TEXT1                  205
#define IDS_GMGR_CANCHNGSLOT            206
#define IDC_SLIDER1                     206
#define IDS_GMGR_CANSLCTSLOT            207
#define IDC_HINT_TEXT2                  207
#define IDS_GMGR_MINPLRS                208
#define IDB_BOARD                       208
#define IDC_HINT_TEXT3                  208
#define IDS_GMGR_MAXPLRS                209
#define IDHINT                          209
#define IDS_GAME_CORRUPTED              210
#define IDNIL                           210
#define IDS_GAME_NO_RESTORE             211
#define IDC_ABOUT_TEXT1                 211
#define IDS_GAME_NO_RESTART             212
#define IDC_ABOUT_TEXT2                 212
#define IDC_GAME_PROP1                  212
#define IDD_HINT                        213
#define IDC_ABOUT_TEXT3                 213
#define IDC_PROP_SCORE                  213
#define IDS_OPT_LDR_ONLY                213
#define IDD_BID                         214
#define IDC_ABOUT_TEXT4                 214
#define IDC_NIL_SCORE1                  214
#define IDS_OPT_STARTED                 214
#define IDD_BN_OPT                      215
#define IDC_ABOUT_TEXT5                 215
#define IDC_NIL_SCORE2                  215
#define IDS_FOLLOW_SUIT                 215
#define IDD_BLINDNIL                    215
#define IDBID                           216
#define IDC_ABOUT_TEXT6                 216
#define IDC_NIL_SCORE3                  216
#define IDS_TRUMP1                      216
#define IDSHOW                          217
#define IDC_NIL_SCORE4                  217
#define IDS_TRUMP2                      217
#define IDC_NIL_SCORE5                  218
#define IDS_HELP_URL                    218
#define IDC_NIL_SCORE6                  219
#define IDS_ABOUT_TITLE                 219
#define IDC_RADIO_WIN_SCORE1            220
#define IDR_MENU_OPT                    220
#define IDS_PARTNER_HINT                220
#define IDC_RADIO_WIN_SCORE2            221
#define IDD_OPTIONS                     221
#define IDS_PARTNER_NIL                 221
#define IDC_NIL_RADIO1                  222
#define IDS_PARTNER_BN                  222
#define IDC_NIL_RADIO2                  223
#define IDS_EXIT_GAME                   223
#define IDC_NIL_RADIO3                  224
#define IDD_HISTORY                     224
#define IDS_WRONG_PLAYER                224
#define IDC_NIL_RADIO4                  225
#define IDS_BIDDING                     225
#define IDC_BN_TEXT                     226
#define IDD_MSGBOX                      226
#define IDS_HINTING                     226
#define IDC_PROP_OK                     227
#define IDS_PASSING                     227
#define IDD_APPROVE                     227
#define IDC_PROP_CANCEL                 228
#define IDC_HISTORY                     228
#define IDS_DEALER                      228
#define IDC_ABOUT_TITLE                 229
#define IDS_BID_CONFIRM                 229
#define IDC_ABOUT_COPYR                 230
#define IDS_CONFIRM                     230
#define IDC_PARTNER_HINT                231
#define IDS_HINT_CONFIRM                231
#define IDC_MESSAGE_TEXT                232
#define IDS_NIL_CONFIRM                 232
#define IDC_RADIO_REV                   233
#define IDS_RECEIVE_PASS                233
#define IDC_RADIO_FWD                   234
#define IDD_PASS                        234
#define IDS_BLIND_NIL                   234
#define IDC_APPROVE                     235
#define IDD_CONFIRM                     235
#define IDS_DOUBLE_NIL                  235
#define IDC_APPROVE_MSG                 236
#define IDS_NIL_BID                     236
#define IDD_TEXT_MSG                    236
#define IDC_NIL_TRICKS_COUNT            237
#define IDS_TEAM_BID                    237
#define IDC_NIL_SOLO                    238
#define IDS_HINT                        238
#define IDS_TAKEN1                      239
#define IDC_CONFIRM_MSG                 240
#define IDS_TAKEN2                      240
#define IDS_PLAYED                      241
#define IDC_BN_HINT                     241
#define IDS_JOINED                      242
#define IDC_TEXT_MSG                    242
#define IDS_BID_FOR_TEAM                243
#define IDS_BLIND_NIL_BID               244
#define IDS_BID_NIL                     245
#define IDS_HINTED                      246
#define IDS_DOUBLE_NIL_BID              247
#define IDS_NIL_TRICKS                  248
#define IDS_TEAM_RESULTS                249
#define IDS_TEAM_SCORE                  250
#define IDS_SANDBAG                     251
#define IDS_BID_SET                     252
#define IDS_TEAM_SUMMARY                253
#define IDS_TEAM_TOTALS                 254
#define IDS_TEAM_WINNERS                255
#define IDS_TIE_GAME                    256
#define IDS_BACKDOOR                    257
#define IDS_DOUBLE_BACKDOOR             258
#define IDS_DBN_SET                     259
#define IDS_BN_SET                      260
#define IDS_DN_SET                      261
#define IDS_NIL_SET                     262
#define IDS_DBN_MADE                    263
#define IDS_BN_MADE                     264
#define IDS_DN_MADE                     265
#define IDS_NIL_MADE                    266
#define IDS_OLDER_VERSION               267
#define ID_MENU_NEW                     32768
#define ID_MENU_SOUND                   32770
#define ID_MENU_GFX                     32771
#define ID_MENU_EXIT                    32772
#define ID_GAMEOPTIONS                  32773
#define ID_GAMEOPTIONS_ABOUTSPADES      32775
#define ID_MENU_HELP                    32776
#define ID_MENU_HISTORY                 32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        237
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         243
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
